version: '3.8'

services:
  app:
    image: maven:3.9.4-eclipse-temurin-21
    volumes:
      - .:/app
      - m2_repository:/root/.m2
    working_dir: /app
    entrypoint: []
    command: sh -c "mvn spring-boot:run"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/medical_appointment_system
      - SPRING_DATASOURCE_USERNAME=mediconnect
      - SPRING_DATASOURCE_PASSWORD=mediconnect_password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DEVTOOLS_RESTART_ENABLED=true

  frontend:
    image: node:22-alpine
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    entrypoint: []
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_TARGET=http://app:8080
    ports:
      - "3001:5173" # Using 3001 to avoid the conflict on 3000
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mediconnect_password
      MYSQL_DATABASE: medical_appointment_system
      MYSQL_USER: mediconnect
      MYSQL_PASSWORD: mediconnect_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  m2_repository:
  db_data:
