version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/medical_appointment_system
      SPRING_DATASOURCE_USERNAME: mediconnect
      SPRING_DATASOURCE_PASSWORD: mediconnect_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mediconnect_password
      MYSQL_DATABASE: medical_appointment_system
      MYSQL_USER: mediconnect
      MYSQL_PASSWORD: mediconnect_password
    ports:
      - "3306:3306" # Expose MySQL port to host for external access (e.g., MySQL Workbench)
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
